Contenedor_proyectoEncuestas/appEncuestas/urls.py
# appEncuestas/urls.py
# version de Django 2.1

from django.urls import path
from django.views import generic
from . import views



app_name = 'espacioEncuestas'
"""
urlpatterns = [
    # ex: /appEncuestas/
    path('', views.index, name='index'),
    # ex: /appEncuestas/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /appEncuestas/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /appEncuestas/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
"""
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

Contenedor_proyectoEncuestas/proyectoEncuestas/urls.py
# proyectoEncuestas/urls.py

from django.urls import include, path
from django.conf.urls import url
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('appEncuestas/', include('appEncuestas.urls')),
]

Contenedor_proyectoEncuestas/appEncuestas/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'		

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # on_delete es obligatorio ponerlo en Django version 2.0 en adelante, antes era por default. Sino da error
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

Contenedor_proyectoEncuestas/appEncuestas/views.py
#  appEncuestas/views.py
# version Django 2.1

from django.template import loader

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = 'appEncuestas/index.html'
    context_object_name = 'latest_question_list'

    def get_querysetAnt(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter( pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'appEncuestas/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'appEncuestas/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

	
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'appEncuestas/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('espacioEncuestas:results', args=(question.id,)))		
	
	

Contenedor_proyectoEncuestas/appEncuestas/templates/appEncuestas/detail.html
<!-- appEncuestas/templates/appEncuestas/detail.html  -->
<!--  mostramos la pagina sin formulario

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

-->

<!-- mostramos la informacion en un formulario  -->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'espacioEncuestas:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<br>
<input type="submit" value="Vote">
</form>

Contenedor_proyectoEncuestas/appEncuestas/templates/appEncuestas/index.html
<!-- appEncuestas/templates/appEncuestas/index.html  -->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'appEncuestas/style.css' %}">

 <h1>  Lista de preguntas  </h1>
 
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
	
<!--        <li><a href="/appEncuestas/{{ question.id }}/">{{ question.question_text }}</a></li> -->
		<li><a href="{% url 'espacioEncuestas:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay preguntas disponibles.</p>
{% endif %}

<!--
<img src="{% static "appEncuestas/images/plantas.jpg" %}" alt="My image">
-->

Contenedor_proyectoEncuestas/appEncuestas/templates/appEncuestas/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'espacioEncuestas:detail' question.id %}">Vote again?</a>